development: &development
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  host: localhost
  pool: 10
  reconnect: true
  database: hrsuite_1554_development

test: &test
  adapter: mysql2
  encoding: utf8
  database: hrsuite_1554_development
  username: root
  password:
  host: localhost
  reconnect: true

production: &production
  adapter: mysql2
  encoding: utf8
  database: hrsuite_1554_development
  username: pa
  password:
  host: localhost
  reconnect: true
